config/routes.rb
Rails.application.routes.draw do
  resources :alliances
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root to: 'root#index'

  resources :couples
  resources :events
  resources :evaluations
  resources :comments
  resources :impressions
  resources :anniversaries
  get '/result', to: 'result#index'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/anniversary.rb
# == Schema Information
#
# Table name: anniversaries
#
#  id         :bigint(8)        not null, primary key
#  day        :integer
#  month      :integer
#  title      :string(255)
#  year       :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  couple_id  :bigint(8)
#
# Indexes
#
#  index_anniversaries_on_couple_id  (couple_id)
#
# Foreign Keys
#
#  fk_rails_...  (couple_id => couples.id)
#

class Anniversary < ApplicationRecord
  belongs_to :couple
end

app/controllers/anniversaries_controller.rb
class AnniversariesController < ApplicationController
  before_action :set_anniversary, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /anniversaries
  # GET /anniversaries.json
  def index
    @anniversaries = Anniversary.all
  end

  # GET /anniversaries/1
  # GET /anniversaries/1.json
  def show
  end

  # GET /anniversaries/new
  def new
    @anniversary = Anniversary.new
  end

  # GET /anniversaries/1/edit
  def edit
  end

  # POST /anniversaries
  # POST /anniversaries.json
  def create
    @anniversary = Anniversary.new(anniversary_params)

    respond_to do |format|
      if @anniversary.save
        format.html { redirect_to @anniversary, notice: 'Anniversary was successfully created.' }
        format.json { render :show, status: :created, location: @anniversary }
      else
        format.html { render :new }
        format.json { render json: @anniversary.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /anniversaries/1
  # PATCH/PUT /anniversaries/1.json
  def update
    respond_to do |format|
      if @anniversary.update(anniversary_params)
        format.html { redirect_to @anniversary, notice: 'Anniversary was successfully updated.' }
        format.json { render :show, status: :ok, location: @anniversary }
      else
        format.html { render :edit }
        format.json { render json: @anniversary.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /anniversaries/1
  # DELETE /anniversaries/1.json
  def destroy
    @anniversary.destroy
    respond_to do |format|
      format.html { redirect_to anniversaries_url, notice: 'Anniversary was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_anniversary
      @anniversary = Anniversary.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def anniversary_params
      params.require(:anniversary).permit(:couple_id, :title, :year, :month, :day)
    end
end

app/helpers/anniversaries_helper.rb
module AnniversariesHelper
end

app/views/anniversaries/_form.html.erb
<%= form_with(model: anniversary, local: true) do |form| %>
  <% if anniversary.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(anniversary.errors.count, "error") %> prohibited this anniversary from being saved:</h2>

      <ul>
      <% anniversary.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :couple_id %>
    <%= form.text_field :couple_id %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :year %>
    <%= form.number_field :year %>
  </div>

  <div class="field">
    <%= form.label :month %>
    <%= form.number_field :month %>
  </div>

  <div class="field">
    <%= form.label :day %>
    <%= form.number_field :day %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/anniversaries/edit.html.erb
<h1>Editing Anniversary</h1>

<%= render 'form', anniversary: @anniversary %>

<%= link_to 'Show', @anniversary %> |
<%= link_to 'Back', anniversaries_path %>

app/views/anniversaries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Anniversaries</h1>

<table>
  <thead>
    <tr>
      <th>Couple</th>
      <th>Title</th>
      <th>Year</th>
      <th>Month</th>
      <th>Day</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @anniversaries.each do |anniversary| %>
      <tr>
        <td><%= anniversary.couple %></td>
        <td><%= anniversary.title %></td>
        <td><%= anniversary.year %></td>
        <td><%= anniversary.month %></td>
        <td><%= anniversary.day %></td>
        <td><%= link_to 'Show', anniversary %></td>
        <td><%= link_to 'Edit', edit_anniversary_path(anniversary) %></td>
        <td><%= link_to 'Destroy', anniversary, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Anniversary', new_anniversary_path %>

app/views/anniversaries/new.html.erb
<h1>New Anniversary</h1>

<%= render 'form', anniversary: @anniversary %>

<%= link_to 'Back', anniversaries_path %>

app/views/anniversaries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Couple:</strong>
  <%= @anniversary.couple %>
</p>

<p>
  <strong>Title:</strong>
  <%= @anniversary.title %>
</p>

<p>
  <strong>Year:</strong>
  <%= @anniversary.year %>
</p>

<p>
  <strong>Month:</strong>
  <%= @anniversary.month %>
</p>

<p>
  <strong>Day:</strong>
  <%= @anniversary.day %>
</p>

<%= link_to 'Edit', edit_anniversary_path(@anniversary) %> |
<%= link_to 'Back', anniversaries_path %>