config/routes.rb
Rails.application.routes.draw do
  resources :alliances
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root to: 'root#index'

  resources :couples
  resources :events
  resources :evaluations
  resources :comments
  resources :impressions
  resources :anniversaries
  get '/result', to: 'result#index'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/alliance.rb
# == Schema Information
#
# Table name: alliances
#
#  id         :bigint(8)        not null, primary key
#  logo       :string(255)
#  message    :text(65535)
#  name       :string(255)      not null
#  url        :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Alliance < ApplicationRecord
end

app/controllers/alliances_controller.rb
class AlliancesController < ApplicationController
  before_action :set_alliance, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /alliances
  # GET /alliances.json
  def index
    @alliances = Alliance.all
  end

  # GET /alliances/1
  # GET /alliances/1.json
  def show
  end

  # GET /alliances/new
  def new
    @alliance = Alliance.new
  end

  # GET /alliances/1/edit
  def edit
  end

  # POST /alliances
  # POST /alliances.json
  def create
    @alliance = Alliance.new(alliance_params)

    respond_to do |format|
      if @alliance.save
        format.html { redirect_to @alliance, notice: 'Alliance was successfully created.' }
        format.json { render :show, status: :created, location: @alliance }
      else
        format.html { render :new }
        format.json { render json: @alliance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /alliances/1
  # PATCH/PUT /alliances/1.json
  def update
    respond_to do |format|
      if @alliance.update(alliance_params)
        format.html { redirect_to @alliance, notice: 'Alliance was successfully updated.' }
        format.json { render :show, status: :ok, location: @alliance }
      else
        format.html { render :edit }
        format.json { render json: @alliance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alliances/1
  # DELETE /alliances/1.json
  def destroy
    @alliance.destroy
    respond_to do |format|
      format.html { redirect_to alliances_url, notice: 'Alliance was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_alliance
      @alliance = Alliance.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def alliance_params
      params.require(:alliance).permit(:logo, :url, :name, :message)
    end
end

app/helpers/alliances_helper.rb
module AlliancesHelper
end

app/views/alliances/_form.html.erb
<%= form_with(model: alliance, local: true) do |form| %>
  <% if alliance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(alliance.errors.count, "error") %> prohibited this alliance from being saved:</h2>

      <ul>
      <% alliance.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :logo %>
    <%= form.text_field :logo %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :message %>
    <%= form.text_area :message %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/alliances/edit.html.erb
<h1>Editing Alliance</h1>

<%= render 'form', alliance: @alliance %>

<%= link_to 'Show', @alliance %> |
<%= link_to 'Back', alliances_path %>

app/views/alliances/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Alliances</h1>

<table>
  <thead>
    <tr>
      <th>Logo</th>
      <th>Url</th>
      <th>Name</th>
      <th>Message</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @alliances.each do |alliance| %>
      <tr>
        <td><%= alliance.logo %></td>
        <td><%= alliance.url %></td>
        <td><%= alliance.name %></td>
        <td><%= alliance.message %></td>
        <td><%= link_to 'Show', alliance %></td>
        <td><%= link_to 'Edit', edit_alliance_path(alliance) %></td>
        <td><%= link_to 'Destroy', alliance, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Alliance', new_alliance_path %>

app/views/alliances/new.html.erb
<h1>New Alliance</h1>

<%= render 'form', alliance: @alliance %>

<%= link_to 'Back', alliances_path %>

app/views/alliances/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Logo:</strong>
  <%= @alliance.logo %>
</p>

<p>
  <strong>Url:</strong>
  <%= @alliance.url %>
</p>

<p>
  <strong>Name:</strong>
  <%= @alliance.name %>
</p>

<p>
  <strong>Message:</strong>
  <%= @alliance.message %>
</p>

<%= link_to 'Edit', edit_alliance_path(@alliance) %> |
<%= link_to 'Back', alliances_path %>